# Generated by Django 6.0 on 2025-12-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('available_stock', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('tax_percentage', models.FloatField()),
            ],
        ),
    ]
