# Generated by Django 6.0 on 2025-12-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_customer_billitem_bill_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_bill_sent',
            field=models.BooleanField(default=False),
        ),
    ]
